before_script:
  - eval `ssh-agent -s` && ssh-add
  - sh bootstrap.sh
  - bin/buildout -N
  - bin/buildout -N remotes:branch=$CI_COMMIT_REF_NAME
  - bin/develop up --force

stages:
  - test


test_sanbox_true:
  stage: test
  variables:
    SANDBOX_MODE: 'True'
  script:
    - bin/py.test openprocurement/bridge/frameworkagreement/tests/ --cov=openprocurement/bridge/frameworkagreement


test_sanbox_false:
  stage: test
  script:
    - bin/py.test openprocurement/bridge/frameworkagreement/tests/ --cov=openprocurement/bridge/frameworkagreement